"""Pydantic artifact contracts. Every agent output is validated against one."""

from ases.contracts.artifacts import (
    CONTRACTS,
    Ambiguity,
    AmbiguityRegister,
    ArchitectureDecision,
    CodePatch,
    DesignSpec,
    DocsPatch,
    FileChange,
    Finding,
    ImpactReport,
    MigrationPlan,
    PolicyViolation,
    ReleaseReport,
    RequirementSpec,
    ReviewReport,
    RunSummary,
    SolutionSkeleton,
    TaskGraph,
    TaskSpec,
    TestSuite,
)
from ases.contracts.base import ArtifactModel

__all__ = [
    "CONTRACTS",
    "Ambiguity",
    "AmbiguityRegister",
    "ArchitectureDecision",
    "ArtifactModel",
    "CodePatch",
    "DesignSpec",
    "DocsPatch",
    "FileChange",
    "Finding",
    "ImpactReport",
    "MigrationPlan",
    "PolicyViolation",
    "ReleaseReport",
    "RequirementSpec",
    "ReviewReport",
    "RunSummary",
    "SolutionSkeleton",
    "TaskGraph",
    "TaskSpec",
    "TestSuite",
]
