"""EF Core migration tools and the static SQL classifier (docs/04 section 4:
the workload's cautious migration pipeline - "the agent generates a
migration, it does not apply one").

`build_ef_migration_tools` mirrors `kernel/tools/dotnet.py`'s shape exactly:
`dotnet ef` is a fixed, named subcommand set behind a `SubprocessRunner`, not
arbitrary shell access - CLAUDE.md section 6. `MIGRATIONS_CLASSIFY` mirrors
`kernel/tools/security.py`'s `SCAN_FOR_SECRETS`: a pure, side-effect-free
static analysis, still registered as a tool rather than a hidden internal
check, so a workflow node can depend on its result exactly like any other
tool's.

**Classifying `OPAQUE`, and why it is not "detect `migrationBuilder.Sql(...)`
in the SQL text":** docs/04 section 4.3 names OPAQUE as "any
`migrationBuilder.Sql(...)` raw block". In practice that call's raw SQL is
inlined verbatim into the *materialized* SQL script by
`dotnet ef migrations script` - `DROP TABLE users` written via
`migrationBuilder.Sql("DROP TABLE users")` is indistinguishable, once
materialized, from the same statement generated by EF Core's normal model
diffing; either way this classifier correctly calls it DESTRUCTIVE. Genuinely
detecting *raw-block provenance* would require inspecting the generated C#
migration file, not the SQL - a second artifact this pipeline does not yet
read (see the module-level docstring in `agents/migration.py` for the
disclosed scope limit this implies).

What OPAQUE means *here* instead: a statement that matches none of the
SAFE/RISKY/DESTRUCTIVE shapes docs/04 section 4.3 enumerates. This is a
deliberate, disclosed reinterpretation - not a shortcut - and it is the
stricter reading of the two: "unrecognized -> deny by default" is exactly the
posture this codebase already takes for an unregistered tool name
(`ToolRegistry`) and an unsafe path (`is_safe_relative_path`), so an
unclassifiable migration statement is refused for the same reason, rather
than silently defaulting to SAFE.
"""

from __future__ import annotations

import re
from collections.abc import Iterable, Mapping
from enum import StrEnum
from typing import Any

from ases.kernel.tools.classification import SideEffect, ToolContext, ToolOutcome, ToolSpec
from ases.kernel.tools.process import SubprocessRunner, default_runner, run_argv


class MigrationClass(StrEnum):
    """docs/04 section 4.3's four handling classes."""

    SAFE = "safe"  # auto-approve
    RISKY = "risky"  # flagged in the diff, human sees rationale
    DESTRUCTIVE = "destructive"  # denied by default, explicit approval required
    OPAQUE = "opaque"  # denied by policy - no approval path at all


_CLASS_RANK: Mapping[MigrationClass, int] = {
    MigrationClass.SAFE: 0,
    MigrationClass.RISKY: 1,
    MigrationClass.DESTRUCTIVE: 2,
    MigrationClass.OPAQUE: 3,
}

# Checked in this order, most severe first: a statement is classified as the
# *first* shape it matches, so e.g. "ADD COLUMN x int NOT NULL DEFAULT 0"
# matches the RISKY not-null-with-default shape before it could ever be
# considered for the SAFE nullable-add-column shape.
_DESTRUCTIVE_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"\bDROP\s+TABLE\b", re.IGNORECASE),
    re.compile(r"\bDROP\s+COLUMN\b", re.IGNORECASE),
    re.compile(r"\bDROP\s+SCHEMA\b", re.IGNORECASE),
    re.compile(r"\bTRUNCATE\b", re.IGNORECASE),
    re.compile(r"\bRENAME\b", re.IGNORECASE),
    re.compile(r"\bDELETE\s+FROM\b", re.IGNORECASE),
)
_RISKY_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"\bADD\s+COLUMN\b.*\bNOT\s+NULL\b", re.IGNORECASE | re.DOTALL),
    # `(?:UNIQUE\s+)?` - a plain `CREATE\s+INDEX` pattern never matches
    # `CREATE UNIQUE INDEX` (`UNIQUE` sits between the two keywords), which
    # is exactly the shape EF Core emits for any unique constraint - the
    # `ShortCode` column here needs precisely one. Every migration
    # containing it fell through every SAFE/RISKY/DESTRUCTIVE pattern to
    # OPAQUE before this, and OPAQUE has "no approval path at all"
    # (`agents/migration.py`'s `OpaqueMigrationRejectedError`) - failing the
    # entire run on what both docs/04 section 4.3 and this table's own SAFE
    # counterpart below already agree is at worst RISKY, never unclassifiable.
    re.compile(r"\bCREATE\s+(?:UNIQUE\s+)?INDEX\b(?!\s+CONCURRENTLY)", re.IGNORECASE),
    re.compile(r"\bALTER\s+COLUMN\b.*\bTYPE\b", re.IGNORECASE | re.DOTALL),
    re.compile(r"\bVALIDATE\s+CONSTRAINT\b", re.IGNORECASE),
)
_SAFE_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"\bCREATE\s+TABLE\b", re.IGNORECASE),
    re.compile(r"\bADD\s+COLUMN\b", re.IGNORECASE),  # RISKY's NOT NULL shape is checked first
    re.compile(r"\bCREATE\s+(?:UNIQUE\s+)?INDEX\s+CONCURRENTLY\b", re.IGNORECASE),
    re.compile(r"\bADD\s+CONSTRAINT\b.*\bNOT\s+VALID\b", re.IGNORECASE | re.DOTALL),
    re.compile(r"\bCREATE\s+SEQUENCE\b", re.IGNORECASE),
    # EF Core's own fixed boilerplate, present in every `dotnet ef migrations
    # script` output regardless of what the migration actually changes -
    # transaction control and the framework's own bookkeeping row, neither
    # of which alters application schema or data. Without these, *every*
    # real EF Core migration was classified OPAQUE (the worst statement
    # wins - `worst_of`) purely from its own wrapper, never from anything
    # the migration itself does. Found by checking this classifier against
    # `dotnet ef migrations script`'s actual real-world output shape, not
    # only the single-statement snippets the existing unit tests used.
    re.compile(r"^\s*(?:START|BEGIN)\s+TRANSACTION\b", re.IGNORECASE),
    re.compile(r"^\s*COMMIT\b", re.IGNORECASE),
    re.compile(r'\bINSERT\s+INTO\s+"?__EFMigrationsHistory"?', re.IGNORECASE),
)


def classify_statement(statement: str) -> MigrationClass:
    """One SQL statement's class, per docs/04 section 4.3's table."""
    if any(p.search(statement) for p in _DESTRUCTIVE_PATTERNS):
        return MigrationClass.DESTRUCTIVE
    if any(p.search(statement) for p in _RISKY_PATTERNS):
        return MigrationClass.RISKY
    if any(p.search(statement) for p in _SAFE_PATTERNS):
        return MigrationClass.SAFE
    return MigrationClass.OPAQUE


def worst_of(classes: Iterable[MigrationClass]) -> MigrationClass:
    ranked = sorted(classes, key=lambda c: _CLASS_RANK[c])
    return ranked[-1] if ranked else MigrationClass.SAFE


def classify_migration(sql: str) -> MigrationClass:
    """The whole migration's class: the worst of every statement in it, so
    one `DROP COLUMN` amid ten additive statements still marks the entire
    migration DESTRUCTIVE. Splitting on `;` is a deliberately simple
    statement boundary - sufficient for the additive/blocking/destructive
    shapes docs/04 section 4.3 enumerates, not a full SQL parser."""
    statements = [s for s in sql.split(";") if s.strip()]
    if not statements:
        return MigrationClass.SAFE
    return worst_of(classify_statement(s) for s in statements)


async def _classify(args: Mapping[str, Any], ctx: ToolContext) -> ToolOutcome:
    classification = classify_migration(str(args["sql"]))
    return ToolOutcome(
        ok=classification is not MigrationClass.OPAQUE,
        output={"classification": classification.value},
        error=(
            None
            if classification is not MigrationClass.OPAQUE
            else (
                "migration contains one or more statements this classifier does not "
                "recognize as safe, risky, or destructive; denied by default "
                "(docs/04 section 4.3)"
            )
        ),
    )


#: Pure static analysis, no subprocess involved - registered directly like
#: `security.SCAN_FOR_SECRETS`, not built via a runner factory.
MIGRATIONS_CLASSIFY = ToolSpec(
    name="migrations.classify",
    handler=_classify,
    idempotent=True,
    side_effect=SideEffect.NONE,
)


def _ef_targeting_args(args: Mapping[str, Any]) -> list[str]:
    """`--project`/`--startup-project`, appended when given.

    Real, disclosed gap this closes: with a single project in `cwd`, `dotnet
    ef` auto-discovers it happily, which is all the existing tests exercise -
    but a real solution has several projects side by side (`ScaffoldAgent`
    now creates a genuine multi-project `.sln`), and `dotnet ef` then refuses
    to guess which one holds the `DbContext` or which one is runnable. Both
    args are optional here (backward compatible with a caller that omits
    them); `agents/migration.py` is what actually supplies them, deriving the
    targets from `SolutionSkeleton.projects` by naming convention.
    """
    argv: list[str] = []
    project = args.get("project")
    startup_project = args.get("startup_project")
    if project:
        argv += ["--project", str(project)]
    if startup_project:
        argv += ["--startup-project", str(startup_project)]
    return argv


def build_ef_migration_tools(runner: SubprocessRunner = default_runner) -> tuple[ToolSpec, ...]:
    """The three `dotnet ef` subcommands docs/04 section 4.6 names. Only
    `ef.database_update` carries `requires_approval=True` - the tool's own
    declared floor (docs/05 section 3.5) - since it is the pipeline's only
    step with a real side effect against the workload schema; generation and
    scripting (steps 2-3) touch no database at all.

    Live enforcement of that approval is `workflows/greenfield.yaml`'s
    `migration_gate` node, placed before the `ef_database_update` tool node -
    the same graph-level gate mechanism gate1/gate2/gate3 already use.
    `requires_approval` on the `ToolSpec` itself documents the policy floor
    (docs/04 section 4.6's table; exercised by `kernel.policy.PolicyEngine`
    tests) but, like every other tool node in this codebase today, is not
    independently re-checked by `ToolRegistry.invoke` at call time - see
    `agents/migration.py`'s module docstring for this disclosed gap.
    """

    async def ef_migrations_add(args: Mapping[str, Any], ctx: ToolContext) -> ToolOutcome:
        name = str(args["name"])
        argv = ["dotnet", "ef", "migrations", "add", name, *_ef_targeting_args(args)]
        return await run_argv(runner, argv, ctx)

    async def ef_migrations_script(args: Mapping[str, Any], ctx: ToolContext) -> ToolOutcome:
        # No `-o`: the SQL is emitted to stdout, which `ToolOutcome.output`
        # already captures - avoids a filesystem round trip to read it back.
        argv = [
            "dotnet",
            "ef",
            "migrations",
            "script",
            "--idempotent",
            *_ef_targeting_args(args),
        ]
        return await run_argv(runner, argv, ctx)

    async def ef_database_update(args: Mapping[str, Any], ctx: ToolContext) -> ToolOutcome:
        argv = ["dotnet", "ef", "database", "update", *_ef_targeting_args(args)]
        return await run_argv(runner, argv, ctx)

    return (
        ToolSpec(
            name="ef.migrations_add",
            handler=ef_migrations_add,
            idempotent=False,  # re-running without a fresh name fails on an existing migration
            side_effect=SideEffect.SANDBOX,
            compensator="delete_migration_files",
            # 300s, not the 60s default: `dotnet ef migrations add` runs a
            # full design-time build under the hood before it can even start
            # (EF Core needs the project compiled to discover the DbContext),
            # the same cost `kernel/tools/dotnet.py`'s `dotnet.build` was
            # deliberately given 300s for. `migration` has no `ON_FAILURE`
            # recovery edge, so a timeout here - like any other failure -
            # would crash the entire run outright; found by reasoning about
            # this node's actual cost before a live run could hit it, the
            # same way issues #12-#14 were found.
            timeout_s=300.0,
        ),
        ToolSpec(
            name="ef.migrations_script",
            handler=ef_migrations_script,
            idempotent=True,
            side_effect=SideEffect.NONE,  # `script` touches no database
            timeout_s=300.0,  # same design-time-build cost as ef.migrations_add above
        ),
        ToolSpec(
            name="ef.database_update",
            handler=ef_database_update,
            idempotent=False,
            side_effect=SideEffect.EXTERNAL,
            requires_approval=True,
            compensator="down_migration_or_schema_restore",
            timeout_s=120.0,
        ),
    )
